[package]
name = "pixel-monkey-contract"
version = "1.0.0"
authors = []

[addresses]
    aptos_minting="_"
    admin="_"
    user="0x1338"
    deployer="0xc6fe44401ff4d613d72a6f49454005bead594d017aab1a7e920e41263286e2a6"
[dev-addresses]

[dependencies]
    AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
    AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
[dev-dependencies]
